### ISSUE TITLE
Error: Plugin did not respond

### ISSUE THREAD

**Issue by Crush-Steelpunch** [larstobi/terraform-provider-multipass#1]
When I'm trying to launch multiple similar it always seems to throw an error about the plugin not responding

```bash
│ Error: Plugin did not respond
│
│   with multipass_instance.swarm-manager,
│   on main.tf line 14, in resource "multipass_instance" "swarm-manager":
│   14: resource "multipass_instance" "swarm-manager" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange
│ call. The plugin logs may contain more details.

```

I'm using in on Windows 11 with multipass 1.9.1+win and terraform v1.2.
[logs.txt](https://github.com/larstobi/terraform-provider-multipass/files/9091989/logs.txt)
4

**Comment by Crush-Steelpunch** [comment]
[main.tf.txt](https://github.com/larstobi/terraform-provider-multipass/files/9092015/main.tf.txt)

**Comment by larstobi** [comment]
@Crush-Steelpunch Thanks for posting the first bug report! 

I've tried to reproduce the error you got, and from what I can gather, one possibility is that the cloud-init file does not exist.

This should produce a nice error message in the provider, but I haven't gotten around to doing that yet.

When running the same parameters on the command line, I got:

`error: No such file: `(and then the file name in the parameter)

Could you please verify that the cloud init file name and path is correct?

**Comment by larstobi** [comment]
Also, please not that the name is "swarm-worker" in both your examples, which will not work, as the instance name must be unique with multipass. This should also produce a nice error message in a future version. :-)

**Comment by Crush-Steelpunch** [comment]
Thank you. It looks like one of the issues was related to this https://github.com/canonical/multipass/issues/885 and upgrading to 1.10 has stopped that. The error output is much improved and the "plugin did not respond" issues have also gone away. I'm still getting issues on create but I don't think they are related to this issue or the multipass plugin.

**Comment by larstobi** [comment]
Nice! Thanks for getting back to me on this.
